apiVersion: v1
kind: ConfigMap
metadata:
  name: idm
  labels:
    {{- with .Values.idm.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- include "idm.labels" . | nindent 4 }}
data:
  IDM_ENVCONFIG_DIRS: {{ .Values.idm.idmEnvconfigDirs | quote }}
  LOGGING_PROPERTIES: {{ .Values.idm.loggingProperties | quote }}
  OPENIDM_ANONYMOUS_PASSWORD: {{ .Values.idm.openidmAnonymousPassword | quote }}
  OPENIDM_AUDIT_HANDLER_JSON_ENABLED: {{ .Values.idm.openidmAuditHandlerJsonEnabled | quote }}
  OPENIDM_AUDIT_HANDLER_STDOUT_ENABLED: {{ .Values.idm.openidmAuditHandlerStdoutEnabled | quote }}
  OPENIDM_CLUSTER_REMOVE_OFFLINE_NODE_STATE: {{ .Values.idm.openidmClusterRemoveOfflineNodeState | quote }}
  OPENIDM_CONFIG_REPO_ENABLED: {{ .Values.idm.openidmConfigRepoEnabled | quote }}
  OPENIDM_ICF_RETRY_DELAYSECONDS: {{ .Values.idm.openidmIcfRetryDelayseconds | quote }}
  OPENIDM_ICF_RETRY_MAXRETRIES: {{ .Values.idm.openidmIcfRetryMaxretries | quote }}
  PROJECT_HOME: {{ .Values.idm.projectHome | quote }}