apiVersion: v1
kind: Service
metadata:
  name: admin-ui
  labels:
    {{- with .Values.adminUi.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}  
  {{- include "admin_ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.adminUi.service.type }}
  selector:
    {{- include "admin_ui.selectorLabels" . | nindent 4 }}
    {{- with .Values.adminUi.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  ports:
  {{- toYaml .Values.adminUi.service.ports | nindent 2}}