apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ds-master-cert
  labels:
    {{- with .Values.secrets.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- include "secrets.labels" . | nindent 4 }}
spec:
  commonName: Master Key
  dnsNames:
  - '*.ds'
  duration: 21600h
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: selfsigned-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  secretName: ds-master-keypair
  secretTemplate:
    labels:
      app: ds-operator
  subject:
    organizations:
    - {{ .Values.certificate.subject.organizations }}
  usages:
  - server auth
  - client auth