apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ds-ssl-cert
  labels:
    {{- with .Values.secrets.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- include "secrets.labels" . | nindent 4 }}
spec:
  commonName: ds
  dnsNames:
  - '*.ds'
  - '*.ds-idrepo'
  - '*.ds-cts'
  duration: 21600h
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: selfsigned-issuer
  privateKey:
    algorithm: ECDSA
  secretName: ds-ssl-keypair
  secretTemplate:
    annotations:
      my-secret-annotation: cert-manager-generated
    labels:
      app: ds-operator
  subject:
    organizations:
    - {{ .Values.certificate.subject.organizations }}
  usages:
  - server auth
  - client auth