apiVersion: secret-agent.secrets.forgerock.io/v1alpha1
kind: SecretAgentConfiguration
metadata:
  name: forgerock-sac
  labels:
    {{- with .Values.secrets.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- include "secrets.labels" . | nindent 4 }}
spec:
  appConfig:
    createKubernetesObjects: true
    secretsManager: none
  secrets:
  - keys:
    - name: ca
      spec:
        distinguishedName:
          commonName: Deployment key
          organization:
          - {{ .Values.certificate.subject.organizations }}
      type: ca
    name: platform-ca
  - keys:
    - name: cacerts
      spec:
        pemFormat: true
        truststoreImportPaths:
        - platform-ca/ca
      type: truststore
    name: truststore-pem
  - keys:
    - name: cacerts
      spec:
        truststoreImportPaths:
        - platform-ca/ca
      type: truststore
    name: truststore
  - keys:
    - name: dirmanager.pw
      spec:
        length: 32
      type: password
    - name: monitor.pw
      spec:
        value: password
      type: literal
    name: ds-passwords
  - keys:
    - name: .keypass
      spec:
        length: 24
      type: password
    - name: .storepass
      spec:
        length: 24
      type: password
    - name: username
      spec:
        value: amadmin
      type: literal
    name: am-passwords
  - keys:
    - name: ssl-key-pair
      spec:
        algorithm: ECDSAWithSHA256
        distinguishedName:
          commonName: ds
          organization:
          - {{ .Values.certificate.subject.organizations }}
        sans:
        - '*.ds'
        - '*.ds-idrepo'
        - '*.ds-cts'
        signedWithPath: platform-ca/ca
      type: keyPair
    - name: master-key-pair
      spec:
        algorithm: SHA256WithRSA
        distinguishedName:
          commonName: Master key
          organization:
          - {{ .Values.certificate.subject.organizations }}
        duration: -72h
        selfSigned: true
      type: keyPair
    - name: keystore.pin
      spec:
        length: 32
      type: password
    - name: keystore
      spec:
        keyPassPath: ds/keystore.pin
        keytoolAliases:
        - cmd: importcert
          name: ca-cert
          sourcePath: platform-ca/ca
        - cmd: importkeystore
          isKeyPair: true
          name: ssl-key-pair
          sourcePath: ds/ssl-key-pair
        - cmd: importkeystore
          isKeyPair: true
          name: master-key
          sourcePath: ds/master-key-pair
        storePassPath: ds/keystore.pin
        storeType: pkcs12
      type: keytool
    name: ds
  - keys:
    - name: AM_AUTHENTICATION_SHARED_SECRET
      spec:
        length: 32
        useBinaryCharacters: true
      type: password
    - name: AM_ENCRYPTION_KEY
      spec:
        length: 24
      type: password
    - name: AM_OIDC_CLIENT_SUBJECT_IDENTIFIER_HASH_SALT
      spec:
        length: 20
      type: password
    - name: AM_PASSWORDS_AMADMIN_CLEAR
      spec:
        length: 24
      type: password
    - name: AM_SELFSERVICE_LEGACY_CONFIRMATION_EMAIL_LINK_SIGNING_KEY
      spec:
        length: 32
        useBinaryCharacters: true
      type: password
    - name: AM_SESSION_STATELESS_ENCRYPTION_KEY
      spec:
        length: 32
        useBinaryCharacters: true
      type: password
    - name: AM_SESSION_STATELESS_SIGNING_KEY
      spec:
        length: 32
        useBinaryCharacters: true
      type: password
    name: am-env-secrets
  - keys:
    - name: keystore.jceks
      spec:
        keyPassPath: am-passwords/.keypass
        keytoolAliases:
        - args:
          - -keyalg
          - RSA
          - -keysize
          - "2048"
          - -sigalg
          - SHA256WITHRSA
          - -validity
          - "3650"
          - -dname
          - CN=rsajwtsigningkey,{{ .Values.certificate.dname }}
          cmd: genkeypair
          name: rsajwtsigningkey
        - args:
          - -keyalg
          - EC
          - -keysize
          - "256"
          - -sigalg
          - SHA256withECDSA
          - -validity
          - "3650"
          - -dname
          - CN=es256test,{{ .Values.certificate.dname }}
          cmd: genkeypair
          name: es256test
        - args:
          - -keyalg
          - EC
          - -keysize
          - "384"
          - -sigalg
          - SHA256withECDSA
          - -validity
          - "3650"
          - -dname
          - CN=es384test,{{ .Values.certificate.dname }}
          cmd: genkeypair
          name: es384test
        - args:
          - -keyalg
          - EC
          - -keysize
          - "521"
          - -sigalg
          - SHA256withECDSA
          - -validity
          - "3650"
          - -dname
          - CN=es512test,{{ .Values.certificate.dname }}
          cmd: genkeypair
          name: es512test
        - args:
          - -keyalg
          - RSA
          - -keysize
          - "2048"
          - -sigalg
          - SHA256WITHRSA
          - -validity
          - "3650"
          - -dname
          - CN=selfserviceenctest,{{ .Values.certificate.dname }}
          cmd: genkeypair
          name: selfserviceenctest
        - args:
          - -keyalg
          - RSA
          - -keysize
          - "2048"
          - -sigalg
          - SHA256WITHRSA
          - -validity
          - "3650"
          - -dname
          - CN=test,{{ .Values.certificate.dname }}
          cmd: genkeypair
          name: test
        - args:
          - -keyalg
          - HMacSHA512
          - -keysize
          - "512"
          cmd: genseckey
          name: hmacsigningtest
        - args:
          - -keyalg
          - HMacSHA512
          - -keysize
          - "256"
          cmd: genseckey
          name: selfservicesigntest
        - args:
          - -keyalg
          - aes
          - -keysize
          - "256"
          cmd: genseckey
          name: directenctest
        - cmd: importpassword
          name: configstorepwd
          sourcePath: am-passwords/.storepass
        - cmd: importpassword
          name: dsameuserpwd
          sourcePath: ds-passwords/dirmanager.pw
        storePassPath: am-passwords/.storepass
        storeType: jceks
      type: keytool
    name: am-keystore
  - keys:
    - name: IDM_PROVISIONING_CLIENT_SECRET
      spec:
        length: 24
      type: password
    - name: IDM_RS_CLIENT_SECRET
      spec:
        length: 24
      type: password
    name: amster-env-secrets
  - keys:
    - name: id_rsa
      type: ssh
    name: amster
  - keys:
    - name: AM_STORES_APPLICATION_PASSWORD
      spec:
        length: 32
      type: password
    - name: AM_STORES_CTS_PASSWORD
      spec:
        length: 32
      type: password
    - name: AM_STORES_USER_PASSWORD
      spec:
        length: 32
      type: password
    name: ds-env-secrets
  - keys:
    - name: OPENIDM_ADMIN_PASSWORD
      spec:
        length: 24
      type: password
    - name: OPENIDM_KEYSTORE_PASSWORD
      spec:
        length: 24
      type: password
    name: idm-env-secrets
  - keys:
    - name: truststore
      spec:
        truststoreImportPaths:
        - platform-ca/ca
      type: truststore
    - name: keystore.jceks
      spec:
        keyPassPath: idm-env-secrets/OPENIDM_KEYSTORE_PASSWORD
        keytoolAliases:
        - args:
          - -keyalg
          - aes
          - -keysize
          - "128"
          cmd: genseckey
          name: openidm-sym-default
        - args:
          - -keyalg
          - HmacSHA256
          - -keysize
          - "256"
          cmd: genseckey
          name: openidm-jwtsessionhmac-key
        - args:
          - -keyalg
          - aes
          - -keysize
          - "128"
          cmd: genseckey
          name: openidm-selfservice-key
        - args:
          - -keyalg
          - RSA
          - -keysize
          - "2048"
          - -sigalg
          - SHA256WITHRSA
          - -validity
          - "3650"
          - -dname
          - CN=server-cert,{{ .Values.certificate.dname }}
          cmd: genkeypair
          name: server-cert
        - args:
          - -keyalg
          - RSA
          - -keysize
          - "2048"
          - -sigalg
          - SHA256WITHRSA
          - -validity
          - "3650"
          - -dname
          - CN=selfservice,{{ .Values.certificate.dname }}
          cmd: genkeypair
          name: selfservice
        - args:
          - -keyalg
          - RSA
          - -keysize
          - "2048"
          - -sigalg
          - SHA256WITHRSA
          - -validity
          - "3650"
          - -dname
          - CN=openidm-localhost,{{ .Values.certificate.dname }}
          cmd: genkeypair
          name: openidm-localhost
        storePassPath: idm-env-secrets/OPENIDM_KEYSTORE_PASSWORD
        storeType: jceks
      type: keytool
    name: idm
