apiVersion: v1
kind: Service
metadata:
  name: login-ui
  labels:
    {{- with .Values.loginUi.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}  
  {{- include "login_ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.loginUi.service.type }}
  selector:
    {{- include "login_ui.selectorLabels" . | nindent 4 }}
    {{- with .Values.loginUi.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  ports:
  {{- toYaml .Values.loginUi.service.ports | nindent 2}}