apiVersion: v1
kind: Service
metadata:
  name: am
  labels:
    {{- with .Values.am.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- include "am.labels" . | nindent 4 }}
spec:
  type: {{ .Values.am.service.type }}
  selector:
    {{- include "am.selectorLabels" . | nindent 4 }}
    {{- with .Values.am.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  ports:
  {{- toYaml .Values.am.service.ports | nindent 2}}