apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-utils
  labels:
    {{- with .Values.base.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- include "base.labels" . | nindent 4 }}
data:
  config-upgrader.sh: |-
    {{- .Files.Get "scripts/config_upgrader.sh" | nindent 4 }}
  git-clone.sh: |-
    {{- .Files.Get "scripts/git_clone.sh" | nindent 4 }}
  git-merge-all.sh: |-
    {{- .Files.Get "scripts/git_merge_all.sh" | nindent 4 }}
  git-sync.sh: |-
    {{- .Files.Get "scripts/git_sync.sh" | nindent 4 }}
  logback.xml: |-
    {{- .Files.Get "scripts/logback.xml" | nindent 4 }}
  tar-config.sh: |-
    {{- .Files.Get "scripts/tar_config.sh" | nindent 4 }}