apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forgerock
  labels:
    {{- with .Values.base.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- include "base.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.platformConfig.certIssuer }}
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/body-size: 64m
    nginx.ingress.kubernetes.io/enable-cors: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 64m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/send-timeout: "600"
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-name: route
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.platformConfig.fqdn }}
    http:
      paths:
      - backend:
          service:
            name: am
            port:
              number: 80
        path: /am
        pathType: Prefix
      - backend:
          service:
            name: idm
            port:
              number: 80
        path: /openidm
        pathType: Prefix
      - backend:
          service:
            name: idm
            port:
              number: 80
        path: /upload
        pathType: Prefix
      - backend:
          service:
            name: idm
            port:
              number: 80
        path: /export
        pathType: Prefix
      - backend:
          service:
            name: idm
            port:
              number: 80
        path: /admin
        pathType: Prefix
      - backend:
          service:
            name: idm
            port:
              number: 80
        path: /openicf
        pathType: Prefix
      - backend:
          service:
            name: end-user-ui
            port:
              number: 8080
        path: /enduser
        pathType: Prefix
      - backend:
          service:
            name: admin-ui
            port:
              number: 8080
        path: /platform
        pathType: Prefix
      - backend:
          service:
            name: login-ui
            port:
              number: 8080
        path: /am/XUI
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.platformConfig.fqdn }}
    secretName: {{ .Values.platformConfig.ingressTlsCert }}